server:
  port: 8085

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/fintech
    username: postgres
    password: postgres

grpc:
  port: 9084
  enable-reflection: true