server:
  port: 8083

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/fintech
    username: postgres
    password: postgres

api:
  client:
    origination:
      grpc:
        host: localhost
        port: 9094