server:
  port: 8087

grpc:
  port: 9044
  enable-reflection: true

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/fintech
    username: postgres
    password: postgres

pg:
  client:
    pe:
      grpc:
        host: localhost
        port: 9084
    origination:
      grpc:
        host: localhost
        port: 9094