server:
  port: 8084

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/fintech
    username: postgres
    password: postgres

grpc:
  port: 9094
  enable-reflection: true

origination:
  client:
    scoring:
      grpc:
        host: localhost
        port: 9074
    pe:
      grpc:
        host: localhost
        port: 9084
    pg:
      grpc:
        host: localhost
        port: 9044
